# Generated by Django 4.2 on 2023-05-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_choice_choice_text_remove_choice_is_correct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_4',
            field=models.TextField(),
        ),
    ]
