# Generated by Django 4.2 on 2023-05-31 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0007_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='student',
            field=models.ManyToManyField(to='home.student'),
        ),
        migrations.AddField(
            model_name='homework',
            name='student',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
