# Generated by Django 4.2 on 2023-06-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_examstudent_delete_examattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examstudent',
            name='score',
            field=models.SmallIntegerField(),
        ),
    ]
