# Generated by Django 4.2 on 2023-06-07 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_question_secttion_question_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='question_bank',
            new_name='questions',
        ),
    ]
